# Generated by Django 3.0.6 on 2021-02-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='nxtquestion',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
