# Generated by Django 3.0.6 on 2021-02-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbc', '0002_questions_nxtquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='nxtquestion',
        ),
    ]
