# Generated by Django 3.0.6 on 2021-02-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbc', '0003_remove_questions_nxtquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='option1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option4',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questions',
            field=models.CharField(max_length=150),
        ),
    ]
