# Generated by Django 3.0.6 on 2021-02-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbc', '0005_auto_20210205_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='correctAnswer',
            field=models.CharField(default='hello', max_length=30),
        ),
        migrations.AddField(
            model_name='questions',
            name='fiftyFiftyId1',
            field=models.CharField(default='h', max_length=1),
        ),
        migrations.AddField(
            model_name='questions',
            name='fiftyFiftyId2',
            field=models.CharField(default='h', max_length=1),
        ),
    ]
