# Generated by Django 3.0.6 on 2021-04-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbc', '0006_auto_20210205_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('givenname', models.CharField(max_length=50)),
                ('familyName', models.CharField(max_length=20)),
                ('image_url', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
